# Name as it appears on the Actions tab of GitHub (for current repo; this get's ignored if called from another repo)
name: 'Unit Tests'

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    paths:
      # You should add paths for files that would be considered part of the program or work-product
      - '.github/workflows/unit-tests.yml'
      - '**.sln'
      - '**.csproj'
      - '**.cs'
      - '**.runsettings'
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - pre/rc
      - beta
      - alpha
      - 'releases/**'
    paths:
      # You should add paths for files that would be considered part of the program or work-product
      - '.github/workflows/unit-tests.yml'
      - '**.sln'
      - '**.csproj'
      - '**.cs'
      - '**.runsetting'

jobs:
  test:
    name: Shared Workflow
    uses: jaffa-nj/.github/.github/workflows/units-dotnet.yml@v1.0.0 # x-release-please-version
    with:
      runs-on: '["self-hosted","windows"]'
      working-directory: "./"
    secrets: inherit
