# Name as it appears on the Actions tab of GitHub (for current repo; this get's ignored if called from another repo)
name: 'Validate Commit Title'

# Controls when the workflow will run
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  commit_title:
    name: Shared Workflow
    uses: jaffa-nj/.github/.github/workflows/conventional-commits.yml@v0.1.1 # x-release-please-version
