settings:

labels:

branch_protections:

environments:

secrets:

variables:

batch_file_operations:
  - target_branch: main
    commit_msg: 'ci(standards): Update dotnet Workflows'
    files:
      - src_file: standardized-workflows/r-lang/.pre-commit-config.yaml
        dest_file: .pre-commit-config.yaml
