name: 'Code-Owners are Team(s)'

on:
  workflow_call:
    inputs:
      runs-on:
        description: Additional required tags for the pipeline agents to use.
        required: true
        type: string
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'releases/**'
      - main
      - rc/*
      - rc
      - beta/*
      - beta
      - alpha/*
      - alpha
    paths:
      - '.github/workflows/codeowners.yml'
      - CODEOWNERS
  pull_request_target:
    paths:
      - '.github/workflows/codeowners.yml'
      - '**/CODEOWNERS'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  get-app-token:
    name: Get GitHub App Token
    uses: ./.github/workflows/get-app-token.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      client-id: ${{ vars.GOV_APP_CLIENT_ID }}
      installation-id: ${{ vars.GOV_APP_INSTALLATION_ID }}
    secrets: inherit

  codeowners:
    name: Verify Code Owners per Governance
    needs: get-app-token
    runs-on: ${{ fromJSON(inputs.runs-on || '[ "ubuntu-latest" ]') }}
    steps:
      #TODO: Deprecated NodeJS Version
      - name: Clean Agent Workspace
        uses: mickem/clean-after-action@v2.0.0

      - name: Decrypt Token
        uses: cloudposse/github-action-secret-outputs@0.1.2
        id: decrypt-token
        with:
          ## PASSWORD is a gpg passphrase stored in Github Secrets.
          secret: ${{ secrets.GOV_APP_PASSWORD }}
          op: decode
          in: ${{ needs.get-app-token.outputs.encrypted-token }}

      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.base_ref }}
      - name: Check for CODEOWNERS file
        uses: andstor/file-existence-action@v2
        id: check_codeowners
        with:
          files: '**/CODEOWNERS'
      - name: Validate CODEOWNERS
        uses: mszostok/codeowners-validator@v0.7.4
        if: steps.check_codeowners.outputs.files_exists
        with:
          checks: "owners,duppatterns,syntax"
          github_access_token: ${{ steps.decrypt-token.outputs.out }}
          owner_checker_owners_must_be_teams: true
          # owner_checker_ignored_owners:
