# TODO: Make this a pre-commit action
name: 'Lint: dotnet'

on:
  workflow_call:
    inputs:
      runs-on:
        description: Additional required tags for the pipeline agents to use.
        required: true
        type: string

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Linting
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      #TODO: Deprecated NodeJS Version
      - name: Clean Agent Workspace
        uses: mickem/clean-after-action@v2.0.0

      - name: Check out Git repository
        uses: actions/checkout@v4.1.7

      - name: Set up .NET
        uses: actions/setup-dotnet@v2 #v3+ has error...
        with:
          dotnet-version: "6.x"

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          dotnet_format: true
