# TODO: Make this a pre-commit action?
name: 'Lint: MarkDown'

on:
  workflow_call:
    inputs:
      runs-on:
        description: Additional required tags for the pipeline agents to use.
        required: true
        type: string
      files:
        description: Markdown files to scan.
        type: string
        required: false
        default: '**/*.{md,markdown}'

jobs:
  run-linters:
    name: Linting MarkDown Files
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      #TODO: Deprecated NodeJS Version
      - name: Clean Agent Workspace
        uses: mickem/clean-after-action@v2.0.0
        
      - name: Check out Git repository
        uses: actions/checkout@v4.1.7
        
      - name: Lint MarkDown files
        uses: articulate/actions-markdownlint@v1
        with:
          files: ${{ inputs.files }}
